---
baseurl: "/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "cywhat's blog"
theme: "LoveIt"
metaDataFormat: "yaml"
algolia:
  index: "cywhat.search"
  key: "9804d4f0420c79d2575243b039a81370"
  appID: "30ZL06YNBE"
---